// Date: 2015/11/20 19:15:48
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package yousui115.bottlemail.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBottleMail extends ModelBase
{
  //fields
    ModelRenderer bottle2;
    ModelRenderer bottle1;
    ModelRenderer cork;
    ModelRenderer mail;

  public ModelBottleMail()
  {
    textureWidth = 64;
    textureHeight = 32;

      bottle2 = new ModelRenderer(this, 0, 0);
      bottle2.addBox(-3F, 0F, -3F, 6, 9, 6);
      bottle2.setRotationPoint(0F, 0F, 0F);
      bottle2.setTextureSize(64, 32);
      bottle2.mirror = true;
      setRotation(bottle2, 0F, 0F, 0F);
      bottle1 = new ModelRenderer(this, 24, 0);
      bottle1.addBox(-1.5F, 0F, -1.5F, 3, 6, 3);
      bottle1.setRotationPoint(0F, -6F, 0F);
      bottle1.setTextureSize(64, 32);
      bottle1.mirror = true;
      setRotation(bottle1, 0F, 0F, 0F);
      cork = new ModelRenderer(this, 24, 9);
      cork.addBox(-1F, 0F, -1F, 2, 2, 2);
      cork.setRotationPoint(0F, -7F, 0F);
      cork.setTextureSize(64, 32);
      cork.mirror = true;
      setRotation(cork, 0F, 0F, 0F);
      mail = new ModelRenderer(this, 36, 0);
      mail.addBox(-1.5F, 0F, -1.5F, 3, 6, 3);
      mail.setRotationPoint(0F, 2F, 0F);
      mail.setTextureSize(64, 32);
      mail.mirror = true;
      setRotation(mail, 0F, 0F, 0F);
  }

  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    bottle2.render(f5);
    bottle1.render(f5);
    cork.render(f5);
    mail.render(f5);
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  @Override
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
